### ISSUE TITLE
Use sqldb360-23.1   to access the edb360 repository  issue....

### ISSUE THREAD

**Issue by cityvigil** [sqldb360/sqldb360#106]
HI~
   Configure edb360 to access the edb360 repository  some issue....

    I use eadma3 to export Repo  from the source database .
    Then using the latest version of sqldb360-23.1 ,analyzing on the target database (another database).
    run repo_eadam3_clone.sql  on target database use sechma **edb360** 。

    **step 2:  modify sql/custom_config_01.sql**  
```
DEF edb360_sections = '1e';
DEF tool_repo_user = 'edb360';  
```
    **step 3: run edb360.sql **  
```
 sqlplus / as sysdba      
sql>  @edb360.sql T custom_config_01.sql

```

    **I found  issue** : eg:
on  eDB360 1e.14. Reads (per second) Series for Instance 1 (DBA_HIST_SYSSTAT)
 sql :  **with  sysstat_io  as ..... from  DBA_HIST_sysstat    ---> why not use     edb360.dba_hist#sysstat**
            FROM sysstat_io h0,
                         DBA_HIST_snapshot s0,
                                    sysstat_io h1,
                                            DBA_HIST_snapshot s1

 then  I test  sqldb360-19.4 this version .  
 This version can be correctly analyzed by edb360's Repo to generate reports.
   
sql is :  FROM edb360.dba_hist#sysstat
              FROM sysstat_io h0,
         edb360.dba_hist#snapshot s0,
         sysstat_io h1,
         edb360.dba_hist#snapshot s1

**Comment by abelmacias** [comment]
eadma3 has not been updated to account for multi-tenant architecture and 23-1 was not updated considering eadma3 either in this first version that support multi-tenant. will see if we can account for it in the next version.

**Comment by cityvigil** [comment]
copy that ~ thanks
