### ISSUE TITLE
SQL Plan Directive Objects spool file missing from eDB360, file 3b

### ISSUE THREAD

**Issue by sqldb360** [sqldb360/sqldb360#18]
Under some unknown circumstances the spool file with SPD objects is missing from edb360 (file 3b).
Such info IS present in SQLd360 for specific SQLs

**Comment by abelmacias** [comment]
caused by another non-displayable character issue now in 3b.

**Comment by mauropagano** [comment]
@abelmacias , want to assign this one to yourself?

**Comment by mauropagano** [comment]
Fixed in #33
