### ISSUE TITLE
licence edition?

### ISSUE THREAD

**Issue by seadba** [sqldb360/sqldb360#2]
cool tool - does this access ash/awr? -

**Comment by sqldb360** [comment]
Yes it does, when you start the top-level script (edb360.sql or sqld360.sql) you'll be asked which license you have (Tuning, Diagnostics or None) and depending on your answer it will access more or less views.

To be honest, without Diagnostics pack you lose a lot of value from the tools (and from Oracle in general, IMHO)

**Comment by seadba** [comment]
thanks for the fast response - i agree about the benefit of the diagnostics but cost differential between EE and SE is extreme -
