### ISSUE TITLE
Line Chart PL/SQL

### ISSUE THREAD

**Issue by dbarj** [sqldb360/sqldb360#36]
In 9e_one_line_chart.sql (for both EDB and SQLD tools), the Date chart function is generated using:

`
l_line := ', [new Date('||SUBSTR(l_end_time,1,4)||','||(TO_NUMBER(SUBSTR(l_end_time,6,2)) - 1)||','||SUBSTR(l_end_time,9,2)||','||SUBSTR(l_end_time,12,2)||','||SUBSTR(l_end_time,15,2)||','||NVL(SUBSTR(l_end_time,18,2),0)||',0)';
`

This "-1" in the **month** part can generate weird results, specially when the end_date is January (will give back 0 as month and thus create an error). What's the meaning of it? Or it's just a bug?

Regards,
RJ

**Comment by dbarj** [comment]
Just noted that month 0 for this function means Jan. Nevermind..

**Comment by mauropagano** [comment]
:-)
