### ISSUE TITLE
Broken graphs due to CDB changes

### ISSUE THREAD

**Issue by abelmacias** [sqldb360/sqldb360#67]
the CDB changes breaks many sections because of two problems that I so far identified.

Example, In 4d time model It adds 2 new columns , CON_ID at the beginning of the list of columns and CON_NAME at the end. 
Queries that already returned 15 columns break on the line chart because line chart rendering only allows up to 15 columns

2nd issue)  the CON_NAME is VARCHAR2 and line chart rendering only allows NUMBER  columns

3rd issue) It is possible it will break yet in another manner but making the graph unreadable depending on how the data is sorted when multiple containers are used but the first 2 issues need to be fixed first to know.

4rd issue) Some queries were not fully changes and still use DBA_views instead of CDB which makes the collection inconsistent
Ex section 4f Latency Histogram
Line 254   FROM &&awr_object_prefix.event_histogram
Line 282        &&cdb_awr_object_prefix.snapshot 
In the attached file the html work but the line graphs not.

[broken_by_cdb.zip](https://github.com/sqldb360/sqldb360/files/4867541/broken_by_cdb.zip)

**Comment by davidkurtz** [comment]
I have a number of fixes to sections 4a-e that will address these issues.  Mostly I have removed the CDB changes and gone back tot he DBA_HIST views, but in 4a I have added charts of individual pools per PDB.  There is a pull request waiting to be merged.

**Comment by abelmacias** [comment]
[edb360_215153_457443_20200712_2014.zip](https://github.com/sqldb360/sqldb360/files/4913445/edb360_215153_457443_20200712_2014.zip)
There are few issues :
In 4a it is only listing one PDB. hmmm
In 6c the SQLs are duplicated.  See anzqt0yhzvg9z and g9x9sxn8vrk1h. also duplicated in 5c ASH CPU per source and ASH Application "enq: RO…
7b suspiciously does not show anything but the sqlds were collected although some are different that the ones listed in 6c ash top sql like sqlmon_5tyyy49t1rr43_20200712_213259

**Comment by abelmacias** [comment]
The idea of these graphs in 4a is to identify active memory leaks and odd memory  behaviors.
Do we know if and how the memory is being segmented by PDB?
Is it really segmented such that we need to differentiate them ?
Would memory leaks be associated or have some way to controlled  by pdbs such that a memory leak would be confined to a pdb?

**Comment by mauropagano** [comment]
@abelmacias is this resolved?

**Comment by abelmacias** [comment]
The broken graphs were fixed. 
The output of 4a needs more studying.
The duplicate SQLs in 6c could have been because using dba_hist and query presented in different pdbs. group by con_id was removed so it is fixed. may need further review if maybe can be made a top15 per pdb exec'd from root.
7b selection now excludes Statements that a sqld360 cannot be generated or not interesting like DBMS_STATS or from our tools.
