### ISSUE TITLE
SGA stats query not CDB compatible

### ISSUE THREAD

**Issue by simonpane** [sqldb360/sqldb360#80]
Query on line **247** of file `edb360_4a_sga_stats.sql` is not non-CDB compatible.

Providing PR with simple fix for non-CDB (including 11g) compatibility.

**Comment by simonpane** [comment]
Associated PR: #81

**Comment by mauropagano** [comment]
Isn't this fixed by PR #79?

**Comment by simonpane** [comment]
No, I don't think that PR #79 fixed the issue.

Try either the current unstable build or v20.2 against an 11g database - in my testing edb360 will hang (with both unstable and v20.2) on an incomplete SQL statement in section 4a until the fix for PR #81 is included. Due to it not setting all of the variables properly.

**Comment by mauropagano** [comment]
Understood, thanks @simonpane !

**Comment by mauropagano** [comment]
Closing by merging PR #81
